### ISSUE TITLE
Understanding --minConversionEfficiency argument

### ISSUE THREAD

**Issue by TSolDour** [dpryan79/MethylDackel#134]
Hi, 
I wanna keep only cytosines with a methylation coefficient greater than 0.5. Can you confirm that --minConversonEfficiency makes me able to to that ? If I understand well, by fixing --minConversionEfficiency at 0.5, MethylDackel will only keep cytosines in CHH or CHG contexts wich are converted in at least 50% of alignments. Am I wright ?

Thanks for your help !

Thomas.

**Comment by dpryan79** [comment]
If you want to keep cytosines that are over 50% methylated then you want to filter the output rather than use --minConversionEfficiency. The --minConversionEfficiency argument is meant to filter individual alignments according to how well the bisulfite conversion worked on them, which is assessed by there being few if any methylated Cs in a CHH or CHG context.
