### ISSUE TITLE
Is there a description on how methylation is called in MethylDackel

### ISSUE THREAD

**Issue by Divyagash** [dpryan79/MethylDackel#43]
Hi @dpryan79,
                        Thank you for this software, it has been really useful in my research. Since there is no publication on MethylDackel, are there any description on how methylation is called from a BAM file?

**Comment by dpryan79** [comment]
Some day I hope to post something on bioarxiv, but in the interim here's a very brief description:

MethyDackel uses htslib (what powers samtools) to create a "pileup" of bases at each position in the genome. A "pileup" is a reference to the "samtools mpileup" command and can be visualized as a stack of bases covering a position with their corresponding Phred quality scores. MethylDackel then filters this pileup of bases according to base call quality and where they are in their reads (c.f. --OT and such). If the reference base at a given position is a C on either strand and that C is in one of the desired contexts then it's written to the output. 

There are some additional details when one has a paired-end dataset. Namely, one doesn't want to extract the same methylation call from both mates if they overlap. Consequently, in such cases the base call quality of one of the mates is set to 0 so it will be filtered out.  Additionally, the base call quality of the remaining base is adjusted up or down depending on whether both mates agree on the base call or not (this is also how samtools mpileup works).

The mbias subfunction works in a similar manner. It notes when there's apparent methylation and save that as a function of position within each read.

If you need details about anything else related to this tool then feel free to ask. Also, sorry for any typos in this reply, I'm writing this on an iPad rather than a proper computer.

**Comment by Divyagash** [comment]
Thank you for the explanation. Looking forward to the paper!
