### ISSUE TITLE
C>T SNPs

### ISSUE THREAD

**Issue by flay** [dpryan79/MethylDackel#44]
Hi Devon,

Just out of curiosity, how does MethylDackel/PileOMeth handles C>T SNPs in the methylation calling? BisSNP and the newer biscuit  have the ability to distinguish the SNP from the opposite strand in directional sequencing and exclude those SNPs from the methylation calling. Is there a similar way to exclude those SNPs which are unreliable for methylation calling with MethylDackel?  

Thanks!

**Comment by dpryan79** [comment]
Thanks for the question! At the moment this issue is simply ignored, due to this package having been developed in the context of in bred mice, where variants are simply not an issue. It'd be a simple enough thing to implement though, so I'll leave this here as a reminder to do so (I've actually been thinking of doing it for almost 1.5 years, but never had someone outside of my group ask me about it).

**Comment by dpryan79** [comment]
I've implemented a method to do this in the master branch, it'll be part of the next release. The method is fairly simple, though I know it's also used in at least some other tools. Namely, it looks for mismatches in the strand opposite of a `C` and will exclude a site (or CpG/CHG if `--mergeContext` is specified) if the fraction of mismatches is above some desired value (`--maxVariantFrac`). For obvious reasons, there's also a minimum depth required for this (`--minOppositeDepth`).

**Comment by flay** [comment]
Thank you! I will give this a try

**Comment by dpryan79** [comment]
This is now implemented in version 0.3.0 :)
