### ISSUE TITLE
empty output

### ISSUE THREAD

**Issue by antoine4ucsd** [dpryan79/MethylDackel#53]
Hi,
I am very interested in using MethylDackel for my ongoing project looking at CpG in HIV.
I tried to run it on one sample (sorted aln bam file) again its own reference but the result is empty
I guess I am missing something obvious....
Would you mind taking a look at one sample? I can share via dropbox (private email)?
a

Using another method, I extracted the cytosine frequency at each pos so I was expecting to get  non-empty output... 
[C9_CytosineFreq.pdf](https://github.com/dpryan79/MethylDackel/files/1356688/C9_CytosineFreq.pdf)

**Comment by dpryan79** [comment]
Sure, please send the dropbox link to dpryan79@gmail.com

**Comment by dpryan79** [comment]
You have a couple issues going on. Firstly, your MAPQs are all below the default threshold, so you'll need to change that (the `-q` option). Secondly, all of your Cs are on the bottom strand, but you have almost no fragments originating from that strand (unless these were PBAT and the strand information didn't get fixed). Finally, you'll need to change the maximum depth option (`-D` to something like 10000000), since almost all of your alignments are stacked on top of each other.

**Comment by antoine4ucsd** [comment]
thanks for taking the time to look at it! Very much appreciated ++
I will give it a try with your suggested parameters and on other samples. I will keep you informed about how it works.
Best,

**Comment by dpryan79** [comment]
Happy to help, keep in mind that without changing the strand information you'll still have low depth. Not knowing exactly how the experiment was performed I don't know if the inferred strand is really correct.

Also, make sure to use `--CHH` :)

**Comment by antoine4ucsd** [comment]
Got it!

**Comment by antoine4ucsd** [comment]
thank you again!
It did work. I will try to improve the sequencing upfront but this is promising


Best,
a
