### ISSUE TITLE
remove/exclude reads with densely un-converted non-CpG sites

### ISSUE THREAD

**Issue by avilella** [dpryan79/MethylDackel#61]
This is a feature request that comes from a wet lab member dealing with data that seems to suffer from a subpopulation of un-converted reads. Digging a bit, it seems like BS-Seeker2 first, and Bismark later, implemented a `--filter_non_conversion` flag. See:

https://github.com/FelixKrueger/Bismark/issues/76

Given the work done on issue #56 , which seems related to what's needed to implement the feature described here, I wonder if this could be added to methyldackel?

Thanks in advance

**Comment by dpryan79** [comment]
This wouldn't work in the normal `extract`, since that essentially operates on a pileup (so looking at the entire length of a read is pretty annoying). I could write a filtering program, but since Felix already wrote one for Bismark I wonder if that'd just duplicate his work needlessly.

BTW, non-CpG methylation does vary in the human genome in accordance with TAD structure and A/B compartments, so I'm hesitant to filter too stringently and end up wiping out something that's actually biologically there (see [this article from a collaborator of ours](https://www.nature.com/articles/s41467-017-01724-9) as an example).

**Comment by SamERoss** [comment]
Hello,

We currently are also suffering from a small percentage of reads being completely unconverted.  In regards to the `--filter_non_conversion` from Bismark, this uses the methylation call strings from a Bismark generated Bam and so doesnt work for non Bismark Bams. So i am just commenting to also express interest in non_converstion filtering for MethylDackel, even if its just something as simple as removing any read with 100% non conversion. I have also commented on another thread on perRead, as if perRead could be given for CHG and CHH metrics, i could use this to filter the reads as well.

Thanks

**Comment by bwlang** [comment]
@mattsoup built a[ simple tool](
https://github.com/nebiolabs/mark-nonconverted-reads) to mark multiple-C reads in a bwameth bam. The tool can set the vendor-fail bit so MethylDackel will skip the marked reads.
It's not battle tested yet.
